export const APP_CHANGE_LOADING_STATE = 'APP/CHANGE_LOADING_STATE';

export const APP_LOGOUT = 'APP/LOGOUT';

export const APP_GET_PROFILE_REQUEST = 'APP/GET_PROFILE/REQUEST';
export const APP_GET_PROFILE_SUCCESS = 'APP/GET_PROFILE/SUCCESS';
export const APP_GET_PROFILE_ERROR = 'APP/GET_PROFILE/ERROR';

export const APP_UPDATE_PROFILE_REQUEST = 'APP/UPDATE_PROFILE/REQUEST';
export const APP_UPDATE_PROFILE_SUCCESS = 'APP/UPDATE_PROFILE/SUCCESS';
export const APP_UPDATE_PROFILE_ERROR = 'APP/UPDATE_PROFILE/ERROR';

export const APP_GET_CATEGORIES_REQUEST = 'APP/GET_CATEGORIES/REQUEST';
export const APP_GET_CATEGORIES_SUCCESS = 'APP/GET_CATEGORIES/SUCCESS';
export const APP_GET_CATEGORIES_ERROR = 'APP/GET_CATEGORIES/ERROR';

export const APP_GET_GOALS_REQUEST = 'APP/GET_GOALS/REQUEST';
export const APP_GET_GOALS_SUCCESS = 'APP/GET_GOALS/SUCCESS';
export const APP_GET_GOALS_ERROR = 'APP/GET_GOALS/ERROR';

export const APP_ADD_GOAL_REQUEST = 'APP/ADD_GOAL/REQUEST';
export const APP_ADD_GOAL_SUCCESS = 'APP/ADD_GOAL/SUCCESS';
export const APP_ADD_GOAL_ERROR = 'APP/ADD_GOAL/ERROR';

export const APP_UPDATE_GOAL_REQUEST = 'APP/UPDATE_GOAL/REQUEST';
export const APP_UPDATE_GOAL_SUCCESS = 'APP/UPDATE_GOAL/SUCCESS';
export const APP_UPDATE_GOAL_ERROR = 'APP/UPDATE_GOAL/ERROR';

export const APP_DELETE_GOAL_REQUEST = 'APP/DELETE_GOAL/REQUEST';
export const APP_DELETE_GOAL_SUCCESS = 'APP/DELETE_GOAL/SUCCESS';
export const APP_DELETE_GOAL_ERROR = 'APP/DELETE_GOAL/ERROR';

export const APP_GET_ALL_TASKS_REQUEST = 'APP/GET_ALL_TASKS/REQUEST';
export const APP_GET_ALL_TASKS_SUCCESS = 'APP/GET_ALL_TASKS/SUCCESS';
export const APP_GET_ALL_TASKS_ERROR = 'APP/GET_ALL_TASKS/ERROR';

export const APP_GET_TASKS_REQUEST = 'APP/GET_TASKS/REQUEST';
export const APP_GET_TASKS_SUCCESS = 'APP/GET_TASKS/SUCCESS';
export const APP_GET_TASKS_ERROR = 'APP/GET_TASKS/ERROR';

export const APP_ADD_TASK_REQUEST = 'APP/ADD_TASK/REQUEST';
export const APP_ADD_TASK_SUCCESS = 'APP/ADD_TASK/SUCCESS';
export const APP_ADD_TASK_ERROR = 'APP/ADD_TASK/ERROR';

export const APP_UPDATE_TASK_REQUEST = 'APP/UPDATE_TASK/REQUEST';
export const APP_UPDATE_TASK_SUCCESS = 'APP/UPDATE_TASK/SUCCESS';
export const APP_UPDATE_TASK_ERROR = 'APP/UPDATE_TASK/ERROR';

export const APP_DELETE_TASK_REQUEST = 'APP/DELETE_TASK/REQUEST';
export const APP_DELETE_TASK_SUCCESS = 'APP/DELETE_TASK/SUCCESS';
export const APP_DELETE_TASK_ERROR = 'APP/DELETE_TASK/ERROR';

export const APP_GET_REWARDS_REQUEST = 'APP/GET_REWARDS/REQUEST';
export const APP_GET_REWARDS_SUCCESS = 'APP/GET_REWARDS/SUCCESS';
export const APP_GET_REWARDS_ERROR = 'APP/GET_REWARDS/ERROR';

export const APP_ADD_REWARD_REQUEST = 'APP/ADD_REWARD/REQUEST';
export const APP_ADD_REWARD_SUCCESS = 'APP/ADD_REWARD/SUCCESS';
export const APP_ADD_REWARD_ERROR = 'APP/ADD_REWARD/ERROR';

export const APP_UPDATE_REWARD_REQUEST = 'APP/UPDATE_REWARD/REQUEST';
export const APP_UPDATE_REWARD_SUCCESS = 'APP/UPDATE_REWARD/SUCCESS';
export const APP_UPDATE_REWARD_ERROR = 'APP/UPDATE_REWARD/ERROR';

export const APP_DELETE_REWARD_REQUEST = 'APP/DELETE_REWARD/REQUEST';
export const APP_DELETE_REWARD_SUCCESS = 'APP/DELETE_REWARD/SUCCESS';
export const APP_DELETE_REWARD_ERROR = 'APP/DELETE_REWARD/ERROR';

export const APP_GET_HABITS_REQUEST = 'APP/GET_HABITS/REQUEST';
export const APP_GET_HABITS_SUCCESS = 'APP/GET_HABITS/SUCCESS';
export const APP_GET_HABITS_ERROR = 'APP/GET_HABITS/ERROR';

export const APP_ADD_HABIT_REQUEST = 'APP/ADD_HABIT/REQUEST';
export const APP_ADD_HABIT_SUCCESS = 'APP/ADD_HABIT/SUCCESS';
export const APP_ADD_HABIT_ERROR = 'APP/ADD_HABIT/ERROR';
