export const MAIN_CHANGE_LOADING_STATE = 'MAIN/CHANGE_LOADING_STATE';

export const MAIN_GET_GOALS_REQUEST = 'MAIN/GET_GOALS/REQUEST';
export const MAIN_GET_GOALS_SUCCESS = 'MAIN/GET_GOALS/SUCCESS';
export const MAIN_GET_GOALS_ERROR = 'MAIN/GET_GOALS/ERROR';

export const MAIN_CHECK_NEW_GOALS_REQUEST = 'MAIN/CHECK_NEW_GOALS/REQUEST';
export const MAIN_CHECK_NEW_GOALS_SUCCESS = 'MAIN/CHECK_NEW_GOALS/SUCCESS';
export const MAIN_CHECK_NEW_GOALS_ERROR = 'MAIN/CHECK_NEW_GOALS/ERROR';

export const MAIN_EMPTY_NEW_GOALS = 'MAIN/EMPTY_NEW_GOALS';

export const MAIN_GET_MY_GOALS_REQUEST = 'MAIN/GET_MY_GOALS/REQUEST';
export const MAIN_GET_MY_GOALS_SUCCESS = 'MAIN/GET_MY_GOALS/SUCCESS';
export const MAIN_GET_MY_GOALS_ERROR = 'MAIN/GET_MY_GOALS/ERROR';

export const MAIN_ADD_GOAL_REQUEST = 'MAIN/ADD_GOAL/REQUEST';
export const MAIN_ADD_GOAL_SUCCESS = 'MAIN/ADD_GOAL/SUCCESS';
export const MAIN_ADD_GOAL_ERROR = 'MAIN/ADD_GOAL/ERROR';

export const MAIN_GET_COMMENTS_REQUEST = 'MAIN/GET_COMMENTS/REQUEST';
export const MAIN_GET_COMMENTS_SUCCESS = 'MAIN/GET_COMMENTS/SUCCESS';
export const MAIN_GET_COMMENTS_ERROR = 'MAIN/GET_COMMENTS/ERROR';

export const MAIN_GET_MY_COMMENTS_REQUEST = 'MAIN/GET_MY_COMMENTS/REQUEST';
export const MAIN_GET_MY_COMMENTS_SUCCESS = 'MAIN/GET_MY_COMMENTS/SUCCESS';
export const MAIN_GET_MY_COMMENTS_ERROR = 'MAIN/GET_MY_COMMENTS/ERROR';

export const MAIN_GET_ALL_COMMENTS_REQUEST = 'MAIN/GET_ALL_COMMENTS/REQUEST';
export const MAIN_GET_ALL_COMMENTS_SUCCESS = 'MAIN/GET_ALL_COMMENTS/SUCCESS';
export const MAIN_GET_ALL_COMMENTS_ERROR = 'MAIN/GET_ALL_COMMENTS/ERROR';

export const MAIN_ADD_COMMENT_REQUEST = 'MAIN/ADD_COMMENT/REQUEST';
export const MAIN_ADD_COMMENT_SUCCESS = 'MAIN/ADD_COMMENT/SUCCESS';
export const MAIN_ADD_COMMENT_ERROR = 'MAIN/ADD_COMMENT/ERROR';

export const MAIN_REPORT_GOAL_REQUEST = 'MAIN/REPORT_GOAL/REQUEST';
export const MAIN_REPORT_GOAL_SUCCESS = 'MAIN/REPORT_GOAL/SUCCESS';
export const MAIN_REPORT_GOAL_ERROR = 'MAIN/REPORT_GOAL/ERROR';
