export const MAIN_CHANGE_LOADING_STATE = 'MAIN/CHANGE_LOADING_STATE';

export const MAIN_GET_GOALS_REQUEST = 'MAIN/GET_GOALS/REQUEST';
export const MAIN_GET_GOALS_SUCCESS = 'MAIN/GET_GOALS/SUCCESS';
export const MAIN_GET_GOALS_ERROR = 'MAIN/GET_GOALS/ERROR';

export const MAIN_ADD_GOAL_REQUEST = 'MAIN/ADD_GOAL/REQUEST';
export const MAIN_ADD_GOAL_SUCCESS = 'MAIN/ADD_GOAL/SUCCESS';
export const MAIN_ADD_GOAL_ERROR = 'MAIN/ADD_GOAL/ERROR';

export const MAIN_GET_REWARDS_REQUEST = 'MAIN/GET_REWARDS/REQUEST';
export const MAIN_GET_REWARDS_SUCCESS = 'MAIN/GET_REWARDS/SUCCESS';
export const MAIN_GET_REWARDS_ERROR = 'MAIN/GET_REWARDS/ERROR';

export const MAIN_ADD_REWARD_REQUEST = 'MAIN/ADD_REWARD/REQUEST';
export const MAIN_ADD_REWARD_SUCCESS = 'MAIN/ADD_REWARD/SUCCESS';
export const MAIN_ADD_REWARD_ERROR = 'MAIN/ADD_REWARD/ERROR';
