# Generated by Django 3.0.2 on 2020-01-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200126_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='goal_id',
            field=models.IntegerField(null=True),
        ),
    ]
