# Generated by Django 3.0.2 on 2020-01-27 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200126_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='goal',
        ),
        migrations.AddField(
            model_name='goal',
            name='tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='api.Task'),
        ),
    ]
