# Generated by Django 3.0.2 on 2020-01-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200127_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='tasks',
        ),
        migrations.AddField(
            model_name='goal',
            name='tasks',
            field=models.ManyToManyField(to='api.Task'),
        ),
    ]
