# Generated by Django 3.0.2 on 2020-02-11 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200211_0550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='score',
            new_name='points',
        ),
    ]
