# Generated by Django 3.0.2 on 2020-02-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200211_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
