# Generated by Django 3.0.2 on 2020-02-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200212_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='createdAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='createdAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='createdAt',
            field=models.DateTimeField(null=True),
        ),
    ]
