# Generated by Django 3.0.2 on 2020-02-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200210_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.TextField(default=0, max_length=150, null=True),
        ),
    ]
