# Generated by Django 3.0.2 on 2020-02-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200211_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_upgraded',
            field=models.BooleanField(default=False),
        ),
    ]
