# Generated by Django 3.0.2 on 2020-02-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_upgraded'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_option',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
